<?php

namespace App\Http\Controllers\Admin\FileManager;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UploadController extends \UniSharp\LaravelFilemanager\Controllers\UploadController
{
    function upload()
    {
        return parent::upload(); // TODO: Change the autogenerated stub
    }
}
